Update LegitimateURLShortener.txt
DandelionSprout/adfilt pull request #323
Opened 2021-11-02 16:56 UTC by shenzhiming88

Soft it simply.

2021-11-02 17:51 UTC, DandelionSprout commented
I feel `! ——— General block rules ——— !` should be below `! ——— General remove rules ——— !`, and not above it.

2021-11-02 21:17 UTC, iam-py-test requested changes
Thank you for opening this Pull Request

2021-11-02 21:17 UTC, iam-py-test commented on LegitimateURLShortener.txt
> +! ——— General block rules ——— !
```suggestion
! ——— General blocking rules ——— !
```
I feel this should be _Blocking_ but that's just my opinion.

2021-11-02 21:17 UTC, iam-py-test commented on LegitimateURLShortener.txt
> +! https://github.com/the1812/Bilibili-Evolved/issues/2247
I feel this should have a link to the PR where it was added (#320)

2021-11-02 21:17 UTC, iam-py-test commented on LegitimateURLShortener.txt
> +! ——— Specific remove rules ——— !
I agree with Imre

2021-11-03 21:02 UTC, iam-py-test approved these changes
This looks great! Thank you
Merging...

2021-11-03 21:03 UTC, merged